const KEY="cadde_bordro_v2";
const HS_BIRIM=2500,PRIM_BIRIM=7,DIS_BIRIM=1;
function hydratePeople(s){if(!s||!Array.isArray(s.people))return s;s.people.forEach(p=>{if(p.yolVar===undefined)p.yolVar=(p.yolGun||0)>0;if(p.hsVar===undefined)p.hsVar=(p.hsSaat||0)>0;});if(!Array.isArray(s.cezalar))s.cezalar=[];if(!Array.isArray(s.devamsizlik))s.devamsizlik=[];return s;}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s&&Array.isArray(s.people)&&s.people.length)return s;}}catch(e){}return JSON.parse(JSON.stringify(typeof SEED!=="undefined"?SEED:{people:[],cezalar:[],devamsizlik:[]}));}
function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
let state=hydratePeople(load());
let filter="hepsi",editId=null,moveId=null,ozetMode="ayrinti";
function calc(p){const mesai=(p.mesaiSaat||0)*(p.mesaiBirim||0);const hs=p.hsVar?(p.hsSaat||0)*HS_BIRIM:0;const prim=p.kurye?(p.primAdet||0)*PRIM_BIRIM:0;const yol=p.yolVar?(p.yolGun||0)*(p.yolBirim||1200):0;const izin=p.izinTutar||0,yillik=p.yillikTutar||0,dis=(p.disiplinDk||0)*DIS_BIRIM;return{mesai,hs,prim,yol,izin,yillik,dis,toplam:mesai+hs+prim+yol+izin+yillik+dis};}
function tl(n){return(Math.round(n)||0).toLocaleString("tr-TR")+" TL";}
function toast(t){let el=document.getElementById("toast");if(!el){el=document.createElement("div");el.id="toast";el.style.cssText="position:fixed;top:14px;left:50%;transform:translateX(-50%);background:#163528;color:#3dd68c;padding:8px 14px;border-radius:10px;z-index:50";document.body.appendChild(el);}el.textContent=t;el.style.display="block";setTimeout(()=>el.style.display="none",1400);}
function tab(el){document.querySelectorAll(".tab").forEach(t=>t.classList.remove("on"));el.classList.add("on");const id=el.dataset.tab;["liste","hs","kurye","devam","ceza","ozet","finans"].forEach(s=>{const e=document.getElementById("sec-"+s);if(e)e.classList.toggle("hide",s!==id);});if(id==="hs")renderTopluHs();if(id==="kurye")renderKurye();if(id==="devam")renderDevam();if(id==="ceza")renderCeza();if(id==="ozet")renderOzet();if(id==="finans")renderFinans();}
function filt(el){document.querySelectorAll(".pill").forEach(p=>{if(p.dataset.f)p.classList.remove("on");});el.classList.add("on");filter=el.dataset.f;renderListe();}
function visiblePeople(){const q=(document.getElementById("q")?.value||"").toLocaleLowerCase("tr-TR");return state.people.filter(p=>{if(q&&!(p.name||"").toLocaleLowerCase("tr-TR").includes(q))return false;const c=calc(p);if(filter==="kurye"&&!p.kurye)return false;if(filter==="pozitif"&&c.toplam<=0)return false;if(filter==="sifir"&&c.toplam!==0)return false;return true;});}
function renderListe(){const people=visiblePeople();const all=state.people.map(calc);const sum=all.reduce((a,b)=>a+b.toplam,0);const poz=all.filter(x=>x.toplam>0).length;document.getElementById("stats").innerHTML=`<div class="stat"><span>Genel toplam</span><b>${tl(sum)}</b></div><div class="stat"><span>Odemesi olan</span><b>${poz} / ${state.people.length}</b></div>`;const moving=moveId!=null;document.getElementById("list").innerHTML=(moving?`<div class="card"><b>Tasima acik</b></div>`:"")+people.map(p=>{const c=calc(p);const sira=state.people.findIndex(x=>x.id===p.id)+1;const cls=[p.kurye?"kurye":"",p.id===moveId?"moving":"",moving&&p.id!==moveId?"targetish":""].filter(Boolean).join(" ");return `<div class="card ${cls}" onclick="onCardTap(${p.id})"><div class="name"><strong>${sira}. ${p.name}</strong>${p.kurye?'<span class="badge">KURYE</span>':""}</div><div class="tiny">Mesai ${p.mesaiSaat}x${p.mesaiBirim}${p.hsVar?` · HS ${p.hsSaat}x2500`:""}${p.yolVar?` · Yol ${p.yolGun}x${p.yolBirim}`:""}</div><div class="rowtot"><span>Toplam</span><span>${tl(c.toplam)}</span></div><div class="movebar"><button class="btn" onclick="event.stopPropagation();startMove(${p.id})">Tasi</button><button class="btn bad" onclick="event.stopPropagation();delById(${p.id})">Sil</button></div></div>`;}).join("");}
function onCardTap(id){if(moveId!=null){placeMove(id);return;}openEdit(id);}
function startMove(id){moveId=moveId===id?null:id;renderListe();}
function placeMove(id){if(moveId==null||moveId===id){moveId=null;renderListe();return;}const a=state.people.findIndex(p=>p.id===moveId);const b=state.people.findIndex(p=>p.id===id);if(a<0||b<0)return;const [item]=state.people.splice(a,1);state.people.splice(b,0,item);moveId=null;persist();renderListe();}
function hsSet(p,saat){saat=parseFloat(saat)||0;p.hsSaat=saat;p.hsVar=saat>0;}
function renderTopluHs(){const box=document.getElementById("hsList");if(!box)return;const q=(document.getElementById("hsQ")?.value||"").toLocaleLowerCase("tr-TR");const list=state.people.filter(p=>!q||(p.name||"").toLocaleLowerCase("tr-TR").includes(q));box.innerHTML=list.map(p=>{const saat=p.hsVar?(p.hsSaat||0):0;return `<div class="card"><div class="name"><label style="flex-direction:row;align-items:center;gap:8px;color:var(--txt)"><input type="checkbox" class="hsChk" data-id="${p.id}" ${saat>0?"checked":""}/><strong>${p.name}</strong></label><span class="tiny">${saat?(saat+" sa · "+tl(saat*HS_BIRIM)):"0 TL"}</span></div><label>HS saat<input type="number" step="0.5" value="${saat}" onchange="hsTekKaydet(${p.id}, this.value)"/></label></div>`;}).join("");}
function hsTekKaydet(id,val){const p=state.people.find(x=>x.id===id);if(!p)return;hsSet(p,val);persist();renderTopluHs();renderListe();}
function hsCheckedIds(){return[...document.querySelectorAll(".hsChk:checked")].map(el=>Number(el.dataset.id));}
function hsSec(on){document.querySelectorAll(".hsChk").forEach(el=>el.checked=!!on);}
function hsUygulaSecili(){const saat=parseFloat(document.getElementById("hsTopluSaat").value)||0;const ids=new Set(hsCheckedIds());if(!ids.size){toast("Once kisi sec");return;}state.people.forEach(p=>{if(ids.has(p.id))hsSet(p,saat);});persist();renderTopluHs();renderListe();toast(ids.size+" kisiye HS");}
function hsUygulaHepsine(){const saat=parseFloat(document.getElementById("hsTopluSaat").value)||0;const q=(document.getElementById("hsQ")?.value||"").toLocaleLowerCase("tr-TR");let n=0;state.people.forEach(p=>{if(!q||(p.name||"").toLocaleLowerCase("tr-TR").includes(q)){hsSet(p,saat);n++;}});persist();renderTopluHs();renderListe();toast(n+" kisiye HS");}
function hsSifirlaSecili(){const ids=new Set(hsCheckedIds());if(!ids.size){toast("Once kisi sec");return;}state.people.forEach(p=>{if(ids.has(p.id))hsSet(p,0);});persist();renderTopluHs();renderListe();toast("HS sifirlandi");}
function renderKurye(){const list=state.people.filter(p=>p.kurye);const sumAdet=list.reduce((a,p)=>a+(p.primAdet||0),0);document.getElementById("kuryeList").innerHTML=list.map(p=>`<div class="card kurye"><div class="name"><strong>${p.name}</strong></div><label>Prim adet<input type="number" value="${p.primAdet||0}" onchange="setPrim(${p.id},this.value)"/></label></div>`).join("")+`<div class="card"><div class="rowtot"><span>Adet ${sumAdet}</span><span>${tl(sumAdet*PRIM_BIRIM)}</span></div></div>`;}
function setPrim(id,v){const p=state.people.find(x=>x.id===id);p.primAdet=parseFloat(v)||0;persist();renderKurye();renderListe();}
function fillSel(id){const sel=document.getElementById(id);if(!sel)return;const cur=sel.value;sel.innerHTML='<option value="">Kisi sec</option>'+state.people.map(p=>`<option value="${p.name}">${p.name}</option>`).join("");if(cur)sel.value=cur;}
function renderDevam(){fillSel("dKisi");const arr=state.devamsizlik||[];document.getElementById("devamList").innerHTML=arr.map((d,i)=>`<div class="card"><b>${d.kisi}</b><div class="tiny">${d.gun} gun · ${d.not||""}</div><button class="btn bad" onclick="state.devamsizlik.splice(${i},1);persist();renderDevam()">Sil</button></div>`).join("");}
function addDevam(){const kisi=document.getElementById("dKisi").value;if(!kisi){toast("Kisi sec");return;}if(!state.devamsizlik)state.devamsizlik=[];state.devamsizlik.push({kisi,gun:parseFloat(document.getElementById("dGun").value)||1,not:document.getElementById("dNot").value||""});persist();renderDevam();}
function renderCeza(){fillSel("cKisi");const arr=state.cezalar||[];document.getElementById("cezaList").innerHTML=arr.map((c,i)=>`<div class="card"><b>${c.kisi}</b><div class="tiny">${tl(c.tutar)} · ${c.neden||""}</div><button class="btn bad" onclick="state.cezalar.splice(${i},1);persist();renderCeza()">Sil</button></div>`).join("");}
function addCeza(){const kisi=document.getElementById("cKisi").value;if(!kisi){toast("Kisi sec");return;}if(!state.cezalar)state.cezalar=[];state.cezalar.push({kisi,tutar:parseFloat(document.getElementById("cTutar").value)||0,neden:document.getElementById("cNeden").value||""});persist();renderCeza();}
function setOzetMode(el){document.querySelectorAll("[data-oz]").forEach(p=>p.classList.remove("on"));el.classList.add("on");ozetMode=el.dataset.oz;renderOzet();}
function renderOzet(){const all=state.people.map(p=>({p,c:calc(p)})).filter(x=>ozetMode==="kisa"?x.c.toplam>0:true);const sum=all.reduce((a,x)=>a+x.c.toplam,0);document.getElementById("ozetBox").innerHTML=`<b>Ozet</b><div class="tiny">${all.length} kisi · ${tl(sum)}</div><table><tr><th>Ad</th><th>Toplam</th></tr>${all.map(x=>`<tr><td>${x.p.name}</td><td>${tl(x.c.toplam)}</td></tr>`).join("")}</table>`;}
function renderFinans(){const all=state.people.map(calc);document.getElementById("finansBox").innerHTML=`<div class="stats"><div class="stat"><span>Mesai</span><b>${tl(all.reduce((a,b)=>a+b.mesai,0))}</b></div><div class="stat"><span>HS</span><b>${tl(all.reduce((a,b)=>a+b.hs,0))}</b></div><div class="stat"><span>Yol</span><b>${tl(all.reduce((a,b)=>a+b.yol,0))}</b></div><div class="stat"><span>Prim</span><b>${tl(all.reduce((a,b)=>a+b.prim,0))}</b></div></div>`;}
function save(){persist();toast("Kaydedildi");}
function resetData(){if(!confirm("Sifirlansin mi?"))return;localStorage.removeItem(KEY);state=hydratePeople(JSON.parse(JSON.stringify(SEED||{people:[]})));persist();renderListe();}
function openAdd(){editId=null;document.getElementById("modalTitle").textContent="Yeni kisi";fName.value="";fSira.value=state.people.length+1;fMesai.value=0;fMesaiBirim.value=300;fHs.value=0;fPrim.value=0;fYol.value=0;fYolBirim.value=1200;fIzin.value=0;fYillik.value=0;fDisk.value=0;fKurye.value="0";document.getElementById("modal").classList.add("show");}
function openEdit(id){const p=state.people.find(x=>x.id===id);if(!p)return;editId=id;document.getElementById("modalTitle").textContent=p.name;fName.value=p.name;fSira.value=state.people.findIndex(x=>x.id===id)+1;fMesai.value=p.mesaiSaat||0;fMesaiBirim.value=p.mesaiBirim||0;fHs.value=p.hsSaat||0;fPrim.value=p.primAdet||0;fYol.value=p.yolGun||0;fYolBirim.value=p.yolBirim||1200;fIzin.value=p.izinTutar||0;fYillik.value=p.yillikTutar||0;fDisk.value=p.disiplinDk||0;fKurye.value=p.kurye?"1":"0";document.getElementById("primBox").classList.toggle("hide",!p.kurye);document.getElementById("modal").classList.add("show");}
function closeModal(){document.getElementById("modal").classList.remove("show");}
function savePerson(){const obj={name:fName.value.trim()||"Isimsiz",mesaiSaat:parseFloat(fMesai.value)||0,mesaiBirim:parseFloat(fMesaiBirim.value)||0,hsSaat:parseFloat(fHs.value)||0,primAdet:parseFloat(fPrim.value)||0,yolGun:parseFloat(fYol.value)||0,yolBirim:parseFloat(fYolBirim.value)||1200,izinTutar:parseFloat(fIzin.value)||0,yillikTutar:parseFloat(fYillik.value)||0,disiplinDk:parseFloat(fDisk.value)||0,kurye:fKurye.value==="1"};obj.hsVar=obj.hsSaat>0;obj.yolVar=obj.yolGun>0;if(!obj.kurye)obj.primAdet=0;if(editId==null){obj.id=Math.max(0,...state.people.map(p=>p.id))+1;state.people.splice(Math.max(0,(parseInt(fSira.value,10)||1)-1),0,obj);}else{const p=state.people.find(x=>x.id===editId);Object.assign(p,obj,{id:p.id});}persist();closeModal();renderListe();}
function delPerson(){if(editId==null)return;delById(editId);closeModal();}
function delById(id){if(!confirm("Silinsin mi?"))return;state.people=state.people.filter(p=>p.id!==id);persist();renderListe();}
function exportCSV(){const rows=state.people.map(p=>[p.id,p.name,Math.round(calc(p).toplam)].join(";"));const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeffNo;Ad;Toplam\n"+rows.join("\n")],{type:"text/csv;charset=utf-8"}));a.download="cadde-bordro.csv";a.click();}
async function sharePDF(){if(!window.jspdf||!window.jspdf.jsPDF){toast("PDF yok");return;}const doc=new window.jspdf.jsPDF();doc.setFontSize(14);doc.text("Cadde Mesai Listesi",10,12);let y=20;state.people.forEach((p)=>{const c=calc(p);if(c.toplam<=0)return;if(y>280){doc.addPage();y=16;}doc.setFontSize(10);doc.text(p.name+"  "+Math.round(c.toplam)+" TL",10,y);y+=6;});doc.save("cadde-bordro.pdf");}
function ghPush(){toast("GitHub gizli");}function ghPull(){toast("GitHub gizli");}function ghSaveCfg(){}function ghLoadCfg(){}function cloudCopyJson(){navigator.clipboard.writeText(JSON.stringify(state));toast("JSON kopyalandi");}
renderListe();
