function calc(p){const mesai=(p.mesaiSaat||0)*(p.mesaiBirim||0);const hs=p.hsVar?(p.hsSaat||0)*1250:0;const prim=p.kurye?(p.primAdet||0)*PRIM_BIRIM:0;const yol=p.yolVar?(p.yolGun||0)*(p.yolBirim||1200):0;const izin=p.izinTutar||0,yillik=p.yillikTutar||0,dis=(p.disiplinDk||0)*DIS_BIRIM;return{mesai,hs,prim,yol,izin,yillik,dis,toplam:mesai+hs+prim+yol+izin+yillik+dis};}
function renderListe(){const people=visiblePeople();const all=state.people.map(calc);const sum=all.reduce((a,b)=>a+b.toplam,0);const poz=all.filter(x=>x.toplam>0).length;document.getElementById("stats").innerHTML=`<div class="stat"><span>Genel toplam</span><b>${tl(sum)}</b></div><div class="stat"><span>Odemesi olan</span><b>${poz} / ${state.people.length}</b></div>`;const moving=moveId!=null;document.getElementById("list").innerHTML=(moving?`<div class="card"><b>Tasima acik</b></div>`:"")+people.map(p=>{const c=calc(p);const sira=state.people.findIndex(x=>x.id===p.id)+1;const cls=[p.kurye?"kurye":"",p.id===moveId?"moving":"",moving&&p.id!==moveId?"targetish":""].filter(Boolean).join(" ");return `<div class="card ${cls}" onclick="onCardTap(${p.id})"><div class="name"><strong>${sira}. ${p.name}</strong>${p.kurye?'<span class="badge">KURYE</span>':""}</div><div class="tiny">Mesai ${p.mesaiSaat}x${p.mesaiBirim}${p.hsVar?` · HS ${p.hsSaat}x1250`:""}${p.yolVar?` · Yol ${p.yolGun}x${p.yolBirim}`:""}</div><div class="rowtot"><span>Toplam</span><span>${tl(c.toplam)}</span></div><div class="movebar"><button class="btn" onclick="event.stopPropagation();startMove(${p.id})">Tasi</button><button class="btn bad" onclick="event.stopPropagation();delById(${p.id})">Sil</button></div></div>`;}).join("");}
function renderTopluHs(){const box=document.getElementById("hsList");if(!box)return;const q=(document.getElementById("hsQ")?.value||"").toLocaleLowerCase("tr-TR");const list=state.people.filter(p=>!q||(p.name||"").toLocaleLowerCase("tr-TR").includes(q));box.innerHTML=list.map(p=>{const saat=p.hsVar?(p.hsSaat||0):0;return `<div class="card"><div class="name"><label style="flex-direction:row;align-items:center;gap:8px;color:var(--txt)"><input type="checkbox" class="hsChk" data-id="${p.id}" ${saat>0?"checked":""}/><strong>${p.name}</strong></label><span class="tiny">${saat?(saat+" adet · "+tl(saat*1250)):"0 TL"}</span></div><label>HS adet<input type="number" step="0.5" value="${saat}" onchange="hsTekKaydet(${p.id}, this.value)"/></label></div>`;}).join("");}
function fold(s){return(s||"").toLocaleUpperCase("tr-TR").replace(/[İI]/g,"I").replace(/Ş/g,"S").replace(/Ğ/g,"G").replace(/Ü/g,"U").replace(/Ö/g,"O").replace(/Ç/g,"C").replace(/\s+/g," ").trim();}
function findP(name){var f=fold(name);return state.people.find(function(p){return fold(p.name)===f;})||state.people.find(function(p){return fold(p.name).indexOf(f)>=0||f.indexOf(fold(p.name))>=0;});}
function applyPdfData(){
  if(!state||!state.people||!state.people.length)return;
  var hsNames=["ABDULLAH AVCI","BURHAN BAYAKIR","ERDAL CAVDAR","HIKMET ERDOGDU","ERHAN SOFUOGLU","BILAL SURUKLI","UGUR GOKER","BEDRETTIN AVCI","SELAHATTIN AVCI","CANER AVCI","YILMAZ AVCI","RAMAZAN BAYAKIR","ONUR AVCI","CIHAN AVCI","MURAT DAGIDIR","SEYFI CELIK","FEVZI DOLAK","MUHAMMET SOFUOGLU","AYDIN AVCI","CIHAN GENC","ABDULLAH DENERI","HAMIT AKPINAR","SAYIM GUMUS","MUHITTIN OZCELIK","HASAN IPEK","VAHDETTIN AVCI","ERCAN ALTUN","OSMAN CEYLAN","ABDURRAHMAN OZKAN","MENDERES SOFUOGLU"];
  hsNames.forEach(function(n){var p=findP(n);if(p){p.hsSaat=2;p.hsVar=true;}});
  [["AYDIN AVCI",2],["MUHITTIN OZCELIK",4],["ABDURRAHMAN GURKAN",2],["MENDERES SOFUOGLU",2]].forEach(function(x){var p=findP(x[0]);if(p)p.mesaiSaat=x[1];});
  if(!state.devamsizlik)state.devamsizlik=[];
  [["HAKAN ATMACA",2,"Izin donusu ise gelmedi"],["KOÇALAN",1,"2 gun raporlu, 1 gun yazilacak"],["ERHAN SOFUOGLU",1,"Raporlu"]].forEach(function(r){
    var p=findP(r[0])||state.people.find(function(x){return fold(x.name).indexOf(fold(r[0]))>=0;});
    var kisi=p?p.name:r[0];
    var exists=state.devamsizlik.some(function(d){return fold(d.kisi).indexOf(fold(kisi))>=0||fold(kisi).indexOf(fold(d.kisi))>=0;});
    if(!exists)state.devamsizlik.push({kisi:kisi,gun:r[1],not:r[2]});
  });
  persist();
  renderListe();
}
applyPdfData();
