const SEED={period:"Guncel liste",people:[
{id:1,name:"CEMAL ÇELİK",mesaiBirim:320,yillikTutar:8000},
{id:2,name:"ABDULLAH AVCI",mesaiBirim:300,hsSaat:1},
{id:3,name:"CUMHUR YİĞİT",mesaiBirim:320},
{id:4,name:"HÜSAMETTİN KÖRPE",mesaiBirim:320},
{id:5,name:"SALİH USTA",mesaiBirim:320},
{id:6,name:"BURHAN BAYAKIR",mesaiBirim:300,hsSaat:1},
{id:7,name:"ERDAL ÇAVDAR",mesaiBirim:320,hsSaat:1},
{id:8,name:"HİKMET ERDOĞDU",mesaiBirim:300,hsSaat:1},
{id:9,name:"SELİM ORTAHİSAR",mesaiBirim:300},
{id:10,name:"MEHMET EMİN MÜDERRİSOĞLU",mesaiBirim:300},
{id:11,name:"KÖKSAL SOYKAN",mesaiBirim:300},
{id:12,name:"FERHAT AVCI",mesaiBirim:300},
{id:13,name:"ERHAN SOFUOĞLU",mesaiBirim:300,hsSaat:1},
{id:14,name:"HASAN ALİ GERZ",mesaiBirim:320},
{id:15,name:"MUHAMMED CAN SARICI",mesaiBirim:300},
{id:16,name:"BİLAL SÜRÜKLİ",mesaiBirim:220,hsSaat:1},
{id:17,name:"MUHAMMED HASAN KOÇALAN",mesaiBirim:300},
{id:18,name:"UĞUR GÖKER",mesaiBirim:250,kurye:true,hsSaat:1},
{id:19,name:"BEDRETTİN AVCI",mesaiBirim:300,hsSaat:1},
{id:20,name:"EMRE POLAT",mesaiBirim:320},
{id:21,name:"SELAHATTİN AVCI",mesaiBirim:250,hsSaat:1},
{id:22,name:"CANER AVCI",mesaiBirim:320,hsSaat:1},
{id:23,name:"ALİ AKKOCA",mesaiBirim:320,kurye:true},
{id:24,name:"AZAT MYRADOV",mesaiBirim:300},
{id:25,name:"MURAT TORUN",mesaiBirim:270,kurye:true},
{id:26,name:"MEHMET ÇELİK",mesaiBirim:300},
{id:27,name:"YILMAZ AVCI",mesaiBirim:320,hsSaat:1},
{id:28,name:"RAMAZAN BAYAKIR",mesaiBirim:270,hsSaat:1},
{id:29,name:"ONUR AVCI",mesaiBirim:300,hsSaat:1},
{id:30,name:"M. MUHAMMED MUSTAFA BAYAKIR",mesaiBirim:300},
{id:31,name:"CİHAN AVCI",mesaiBirim:300,hsSaat:1},
{id:32,name:"YASİR FURKAN KAVAK",mesaiBirim:300,izinGun:1,izinTutar:2700},
{id:33,name:"SEPİDEH MENNATİ",mesaiBirim:300},
{id:34,name:"MUHAMMET EREN ÇELİK",mesaiBirim:300},
{id:35,name:"MURAT DAĞIDIR",mesaiBirim:300,hsSaat:1},
{id:36,name:"SEYFİ ÇELİK",mesaiBirim:270,kurye:true,hsSaat:1},
{id:37,name:"FEVZİ DOLAK",mesaiBirim:270,kurye:true,hsSaat:1},
{id:38,name:"MUHAMMET SOFUOĞLU",mesaiBirim:320,hsSaat:1},
{id:39,name:"AYDIN AVCI",mesaiBirim:320,mesaiSaat:2,hsSaat:1},
{id:40,name:"HAKAN ATMACA",mesaiBirim:270,kurye:true},
{id:41,name:"CİHAN GENÇ",mesaiBirim:270,kurye:true,hsSaat:1},
{id:42,name:"ABDULLAH DENERİ",mesaiBirim:220,hsSaat:1},
{id:43,name:"HAMİT AKPINAR",mesaiBirim:220,hsSaat:1},
{id:44,name:"ADİL DEMİR ÇELİK",mesaiBirim:300},
{id:45,name:"ABDURRAHMAN KAPAN",mesaiBirim:270,kurye:true},
{id:46,name:"SAYİM GÜMÜŞ",mesaiBirim:270,kurye:true,hsSaat:1},
{id:47,name:"MUHİTTİN ÖZÇELİK",mesaiBirim:270,mesaiSaat:4,hsSaat:1},
{id:48,name:"BAYRAM YETER",mesaiBirim:270,kurye:true},
{id:49,name:"YUNUS EMRE ÇELİK",mesaiBirim:300},
{id:50,name:"RAMAZAN YAVUZ",mesaiBirim:270,kurye:true},
{id:51,name:"ZEYNEP SOFUOĞLU",mesaiBirim:270},
{id:52,name:"MUSTAFA AYDIN",mesaiBirim:270,kurye:true},
{id:53,name:"HASAN İPEK",mesaiBirim:320,hsSaat:1,izinGun:2,izinTutar:5800},
{id:54,name:"KAAN ATASOY",mesaiBirim:220,izinGun:2,izinTutar:4800},
{id:55,name:"ABDURRAHMAN GÜRKAN",mesaiBirim:320,mesaiSaat:2},
{id:56,name:"VAHDETTİN AVCI",mesaiBirim:270,hsSaat:1,izinGun:1,izinTutar:2400},
{id:57,name:"ERCAN ALTUN",mesaiBirim:270,hsSaat:1},
{id:58,name:"OSMAN CEYLAN",mesaiBirim:270,kurye:true,hsSaat:1},
{id:59,name:"SEMİH SOFUOĞLU",mesaiBirim:270},
{id:60,name:"ABDURRAHMAN ÖZKAN",mesaiBirim:270,hsSaat:1},
{id:61,name:"FIRAT AVCI",mesaiBirim:320},
{id:62,name:"MENDERES SOFUOĞLU",mesaiBirim:320,mesaiSaat:2,hsSaat:1},
{id:63,name:"HİCABİ AKYILDIZ",mesaiBirim:300},
{id:64,name:"ABDURRAHMAN BULUT",mesaiBirim:220}
],cezalar:[],devamsizlik:[
{kisi:"HAKAN ATMACA",gun:2,not:"İzin dönüşü işe gelmedi"},
{kisi:"MUHAMMED HASAN KOÇALAN",gun:1,not:"2 gün raporlu, 1 gün yazılacak"},
{kisi:"ERHAN SOFUOĞLU",gun:1,not:"Raporlu"}
]};
